packaging_format = 2

id = "dispatch"
name = "Dispatch"
description.en = "Web-based IRC graphical client"
description.fr = "Client graphique IRC"

version = "0.7~ynh4"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
demo = "https://dispatch.khlieng.com/"
code = "https://github.com/khlieng/dispatch"

[integration]
yunohost = ">= 11.1.16"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "If enabled, Dispatch will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Dispatch sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        in_subdir = false
        arm64.url = "https://github.com/khlieng/dispatch/releases/download/v0.7/dispatch_0.7_linux_arm64.tar.gz"
        arm64.sha256 = "bf68249f5bbcaafa50f4b72c8401dfe858405705f76985d88d2460737235dca3"
        amd64.url = "https://github.com/khlieng/dispatch/releases/download/v0.7/dispatch_0.7_linux_x64.tar.gz"
        amd64.sha256 = "7a94cb965de08919a32523116265e7facb69deaa6cfc916adbb34f4083f9e1d9"
        armhf.url = "https://github.com/khlieng/dispatch/releases/download/v0.7/dispatch_0.7_linux_armv7.tar.gz"
        armhf.sha256 = "07c678c29dea633fe7e372c48cebe1876bfc43b0f7abbd88a55318587994750c"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "dispatch_*_linux_arm64.tar.gz"
        autoupdate.asset.amd64 = "dispatch_*_linux_x64.tar.gz"
        autoupdate.asset.armhf = "dispatch_*_linux_armv7.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
